"""Shared component contract — canonical DTOs + service interfaces.

Generated by the scaffold task. EVERY component imports its types and interfaces
from here (never redefine them) so producers and consumers agree.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, List, Optional, Protocol  # noqa: F401
from uuid import UUID  # noqa: F401

from pydantic import BaseModel

class InstrumentDTO(BaseModel):
    instrument_id: int
    name: str
    nickname: str
    location_id: int
    location_name: str
    vendor_id: int
    vendor_name: str
    type_id: int
    type_name: str
    asset_id: Optional[str] = None
    color: Optional[str] = None
    status: str
    is_favorite: bool
    is_active: bool

class InstrumentCreateDTO(BaseModel):
    name: str
    nickname: str
    location_id: int
    vendor_id: int
    type_id: int
    asset_id: Optional[str] = None
    color: Optional[str] = None
    status: str
    is_active: bool

class InstrumentUpdateDTO(BaseModel):
    name: Optional[str] = None
    nickname: Optional[str] = None
    location_id: Optional[int] = None
    vendor_id: Optional[int] = None
    type_id: Optional[int] = None
    asset_id: Optional[str] = None
    color: Optional[str] = None
    status: Optional[str] = None
    is_active: Optional[bool] = None

class InstrumentFilterDTO(BaseModel):
    nickname: Optional[str] = None
    location_id: Optional[int] = None
    vendor_id: Optional[int] = None
    type_id: Optional[int] = None
    favorites_only: Optional[bool] = None

class LocationDTO(BaseModel):
    location_id: int
    name: str
    is_active: bool

class VendorDTO(BaseModel):
    vendor_id: int
    name: str
    is_active: bool

class TypeDTO(BaseModel):
    type_id: int
    name: str
    is_active: bool

class ReservationPurposeDTO(BaseModel):
    reservation_purpose_id: int
    name: str
    is_active: bool

class ReservationDTO(BaseModel):
    reservation_id: int
    instrument_id: int
    instrument_name: str
    start_datetime: datetime
    end_datetime: datetime
    reservation_purpose_id: int
    purpose_name: str
    requested_by: str
    can_be_overridden: bool
    is_active: bool

class ReservationCreateDTO(BaseModel):
    instrument_id: int
    start_datetime: datetime
    end_datetime: datetime
    reservation_purpose_id: int
    requested_by: Optional[str] = None
    can_be_overridden: bool

class ReservationResultDTO(BaseModel):
    reservation: ReservationDTO
    overridden_ids: list[int]

class AuditLogDTO(BaseModel):
    audit_log_id: int
    actor: str
    timestamp: datetime
    action_type: str
    entity_type: str
    entity_id: int
    description: str

class UsageWarningDTO(BaseModel):
    usage_count: int
    message: str

class SchedulerTimelineDTO(BaseModel):
    instruments: list[InstrumentDTO]
    reservations: list[ReservationDTO]
    start_date: datetime
    end_date: datetime

class DuplicateMasterDataError(Exception):
    """A master data name already exists (case-insensitive normalized)."""
    def __init__(self, entity_type: str = "", name: str = "") -> None:
        super().__init__(entity_type)
        self.entity_type = entity_type
        self.name = name

class ReservationConflictError(Exception):
    """A reservation overlaps a non-overridable existing reservation."""
    def __init__(self, conflicting_reservation_id: Optional[int] = None, message: str = "") -> None:
        super().__init__(message or conflicting_reservation_id)
        self.conflicting_reservation_id = conflicting_reservation_id
        self.message = message or conflicting_reservation_id

class TimeBoundaryError(Exception):
    """Reservation times violate validation rules (end <= start or not on 30-min boundary)."""
    def __init__(self, field: str = "", message: str = "") -> None:
        super().__init__(message or field)
        self.field = field
        self.message = message or field

class InvalidInstrumentStatusError(Exception):
    """An instrument is decommissioned or under maintenance and cannot be scheduled."""
    def __init__(self, instrument_id: Optional[int] = None, status: str = "") -> None:
        super().__init__(instrument_id)
        self.instrument_id = instrument_id
        self.status = status

class NotFoundError(Exception):
    """A requested entity does not exist."""
    def __init__(self, entity_type: str = "", entity_id: Optional[int] = None) -> None:
        super().__init__(entity_type)
        self.entity_type = entity_type
        self.entity_id = entity_id

class InstrumentProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    instrument_id: int
    name: str
    nickname: str
    location_id: int
    vendor_id: int
    type_id: int
    asset_id: str
    color: str
    status: Any
    is_favorite: bool
    is_active: bool

class LocationProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    location_id: int
    name: str
    is_active: bool

class VendorProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    vendor_id: int
    name: str
    is_active: bool

class TypeProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    type_id: int
    name: str
    is_active: bool

class ReservationPurposeProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    reservation_purpose_id: int
    name: str
    is_active: bool

class ReservationProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    reservation_id: int
    instrument_id: int
    start_datetime: datetime
    end_datetime: datetime
    reservation_purpose_id: int
    requested_by: str
    can_be_overridden: bool
    is_active: bool

class AuditLogProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    audit_log_id: int
    actor: str
    timestamp: datetime
    action_type: Any
    entity_type: Any
    entity_id: int
    description: str

class InstrumentServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def create(self, data: InstrumentCreateDTO) -> InstrumentDTO: ...
    def update(self, instrument_id: int, data: InstrumentUpdateDTO) -> InstrumentDTO: ...
    def soft_delete(self, instrument_id: int) -> Any: ...
    def toggle_favorite(self, instrument_id: int) -> bool: ...
    def list_instruments(self, filters: InstrumentFilterDTO) -> list[InstrumentDTO]: ...
    def get_instrument(self, instrument_id: int) -> InstrumentDTO: ...

class MasterDataServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def create_location(self, name: str) -> LocationDTO: ...
    def update_location(self, location_id: int, name: str) -> LocationDTO: ...
    def deactivate_location(self, location_id: int) -> UsageWarningDTO: ...
    def reactivate_location(self, location_id: int) -> LocationDTO: ...
    def list_locations(self, include_inactive: bool) -> list[LocationDTO]: ...
    def create_vendor(self, name: str) -> VendorDTO: ...
    def update_vendor(self, vendor_id: int, name: str) -> VendorDTO: ...
    def deactivate_vendor(self, vendor_id: int) -> UsageWarningDTO: ...
    def list_vendors(self, include_inactive: bool) -> list[VendorDTO]: ...
    def create_type(self, name: str) -> TypeDTO: ...
    def update_type(self, type_id: int, name: str) -> TypeDTO: ...
    def deactivate_type(self, type_id: int) -> UsageWarningDTO: ...
    def list_types(self, include_inactive: bool) -> list[TypeDTO]: ...
    def create_purpose(self, name: str) -> ReservationPurposeDTO: ...
    def update_purpose(self, purpose_id: int, name: str) -> ReservationPurposeDTO: ...
    def deactivate_purpose(self, purpose_id: int) -> UsageWarningDTO: ...
    def reactivate_purpose(self, purpose_id: int) -> ReservationPurposeDTO: ...
    def list_purposes(self, include_inactive: bool) -> list[ReservationPurposeDTO]: ...

class ReservationServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def create(self, data: ReservationCreateDTO) -> ReservationResultDTO: ...
    def list_reservations(self, instrument_id: int, start_date: datetime, end_date: datetime) -> list[ReservationDTO]: ...

class AuditLogServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def log(self, actor: str, action_type: Any, entity_type: Any, entity_id: int, description: str) -> Any: ...
    def list_entries(self) -> list[AuditLogDTO]: ...

class SchedulerServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def get_timeline(self, date: datetime, view: str) -> SchedulerTimelineDTO: ...
