"""Shared component contract — canonical DTOs + service interfaces.

Generated by the scaffold task. EVERY component imports its types and interfaces
from here (never redefine them) so producers and consumers agree.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, List, Optional, Protocol  # noqa: F401
from uuid import UUID  # noqa: F401

from pydantic import BaseModel

class InstrumentData(BaseModel):
    instrument_id: int
    name: str
    nickname: str
    location_id: int
    location_name: str
    vendor_id: int
    vendor_name: str
    type_id: int
    type_name: str
    asset_id: Optional[str] = None
    color: Optional[str] = None
    status: str
    is_active: bool
    is_favorite: bool

class InstrumentCreateData(BaseModel):
    nickname: str
    name: str
    location_id: int
    vendor_id: int
    type_id: int
    asset_id: Optional[str] = None
    color: Optional[str] = None
    status: str
    is_active: bool
    actor: str

class InstrumentUpdateData(BaseModel):
    nickname: Optional[str] = None
    name: Optional[str] = None
    location_id: Optional[int] = None
    vendor_id: Optional[int] = None
    type_id: Optional[int] = None
    asset_id: Optional[str] = None
    color: Optional[str] = None
    status: Optional[str] = None
    is_active: Optional[bool] = None
    actor: str

class InstrumentFilterData(BaseModel):
    nickname: Optional[str] = None
    location_id: Optional[int] = None
    vendor_id: Optional[int] = None
    type_id: Optional[int] = None
    favorites: Optional[bool] = None
    sort_by: Optional[str] = None

class LocationData(BaseModel):
    location_id: int
    name: str
    is_active: bool

class VendorData(BaseModel):
    vendor_id: int
    name: str
    is_active: bool

class TypeData(BaseModel):
    type_id: int
    name: str
    is_active: bool

class PurposeData(BaseModel):
    reservation_purpose_id: int
    name: str
    is_active: bool

class UsageWarning(BaseModel):
    active_instrument_count: int
    active_reservation_count: int

class ReservationCreateData(BaseModel):
    instrument_id: int
    start_time: datetime
    end_time: datetime
    purpose_id: int
    requested_by: str
    can_be_overridden: bool

class ReservationResult(BaseModel):
    reservation_id: int
    overridden_reservation_ids: list[int]

class TimelineData(BaseModel):
    instruments: list[InstrumentData]
    reservations: list[ReservationBlockData]

class ReservationBlockData(BaseModel):
    reservation_id: int
    instrument_id: int
    start_time: datetime
    end_time: datetime
    color: str

class AuditLogData(BaseModel):
    audit_log_id: int
    actor: str
    timestamp: datetime
    action_type: str
    entity_type: str
    entity_id: int
    description: str

class DuplicateError(Exception):
    """Master data name already exists (case/whitespace insensitive)"""
    def __init__(self, entity_type: str = "", name: str = "") -> None:
        super().__init__(entity_type)
        self.entity_type = entity_type
        self.name = name

class ValidationError(Exception):
    """Input validation fails (time boundaries, end > start, required fields)"""
    def __init__(self, field: str = "", message: str = "") -> None:
        super().__init__(message or field)
        self.field = field
        self.message = message or field

class ConflictError(Exception):
    """Reservation conflicts with non-overridable existing reservation"""
    def __init__(self, conflicting_reservation_id: Optional[int] = None, message: str = "") -> None:
        super().__init__(message or conflicting_reservation_id)
        self.conflicting_reservation_id = conflicting_reservation_id
        self.message = message or conflicting_reservation_id

class NotFoundError(Exception):
    """Requested entity does not exist"""
    def __init__(self, entity_type: str = "", entity_id: Optional[int] = None) -> None:
        super().__init__(entity_type)
        self.entity_type = entity_type
        self.entity_id = entity_id

class InvalidStatusError(Exception):
    """Instrument is decommissioned or under maintenance and cannot be scheduled"""
    def __init__(self, instrument_id: Optional[int] = None, status: str = "") -> None:
        super().__init__(instrument_id)
        self.instrument_id = instrument_id
        self.status = status

class InstrumentProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    instrument_id: int
    name: str
    nickname: str
    location_id: int
    vendor_id: int
    type_id: int
    asset_id: str
    color: str
    status: Any
    is_active: bool
    is_favorite: bool

class LocationProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    location_id: int
    name: str
    is_active: bool

class VendorProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    vendor_id: int
    name: str
    is_active: bool

class TypeProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    type_id: int
    name: str
    is_active: bool

class ReservationPurposeProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    reservation_purpose_id: int
    name: str
    is_active: bool

class ReservationProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    reservation_id: int
    instrument_id: int
    start_date_time: datetime
    end_date_time: datetime
    reservation_purpose_id: int
    requested_by: str
    can_be_overridden: bool
    is_active: bool

class AuditLogProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    audit_log_id: int
    actor: str
    timestamp: datetime
    action_type: Any
    entity_type: Any
    entity_id: int
    description: str

class InstrumentServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def create_instrument(self, data: InstrumentCreateData) -> InstrumentData: ...
    def update_instrument(self, instrument_id: int, data: InstrumentUpdateData) -> InstrumentData: ...
    def soft_delete_instrument(self, instrument_id: int, actor: str) -> Any: ...
    def toggle_favorite(self, instrument_id: int) -> bool: ...
    def list_instruments(self, filters: InstrumentFilterData) -> list[InstrumentData]: ...
    def get_instrument(self, instrument_id: int) -> InstrumentData: ...
    def list_schedulable_instruments(self) -> list[InstrumentData]: ...

class MasterDataServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def create_location(self, name: str, actor: str) -> LocationData: ...
    def update_location(self, location_id: int, name: str, actor: str) -> LocationData: ...
    def soft_delete_location(self, location_id: int, actor: str) -> UsageWarning: ...
    def reactivate_location(self, location_id: int, actor: str) -> LocationData: ...
    def list_locations(self, include_inactive: bool) -> list[LocationData]: ...
    def create_vendor(self, name: str, actor: str) -> VendorData: ...
    def update_vendor(self, vendor_id: int, name: str, actor: str) -> VendorData: ...
    def soft_delete_vendor(self, vendor_id: int, actor: str) -> UsageWarning: ...
    def list_vendors(self, include_inactive: bool) -> list[VendorData]: ...
    def create_type(self, name: str, actor: str) -> TypeData: ...
    def update_type(self, type_id: int, name: str, actor: str) -> TypeData: ...
    def soft_delete_type(self, type_id: int, actor: str) -> UsageWarning: ...
    def list_types(self, include_inactive: bool) -> list[TypeData]: ...
    def create_purpose(self, name: str, actor: str) -> PurposeData: ...
    def update_purpose(self, purpose_id: int, name: str, actor: str) -> PurposeData: ...
    def soft_delete_purpose(self, purpose_id: int, actor: str) -> UsageWarning: ...
    def reactivate_purpose(self, purpose_id: int, actor: str) -> PurposeData: ...
    def list_purposes(self, include_inactive: bool) -> list[PurposeData]: ...

class ReservationServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def create_reservation(self, data: ReservationCreateData) -> ReservationResult: ...

class SchedulerServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def get_timeline_data(self, date: date, view: str) -> TimelineData: ...

class AuditServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def record_action(self, action_type: Any, entity_type: Any, entity_id: int, actor: str, description: str) -> Any: ...
    def list_entries(self) -> list[AuditLogData]: ...

class SeedServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def load_seed_data(self) -> Any: ...
