"""Single application entrypoint (generated by the scaffold task).

Composes the plan's component modules by importing their declared seams.

A component that fails to import is FATAL by default: the app refuses to start and
says which seams failed and why. This is deliberate. Skipping a broken component and
carrying on lets the app answer /health while missing whole layers of itself -- live,
an app wired 7 of 11 seams, served its JSON API perfectly, answered 404 for every page,
and was reported as a successful deployment.

Set SHIFT_ALLOW_PARTIAL_SEAMS=1 to start anyway, for the case the tolerance was written
for: a partially built app during development, where most components do not exist yet.
Then /health still reports the truth in `failed`, and answers 503 if nothing wired."""
from __future__ import annotations

import importlib
import logging
import os

from fastapi import APIRouter, FastAPI
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

log = logging.getLogger("app")
app = FastAPI(title="PROJ-2525C8EC-7C87-4A4E-9061-130DA291B8F6")

# Declared component seams the Technical Lead plan wired into this app.
_SEAMS = [
    'models:Base',
    'models:Instrument',
    'models:Location',
    'models:Vendor',
    'models:InstrumentType',
    'models:ReservationPurpose',
    'models:Reservation',
    'models:AuditLog',
    'models:InstrumentStatus',
    'models:AuditActionType',
    'models:AuditEntityType',
    'models:get_db',
    'services:InstrumentService',
    'services:ReservationService',
    'services:MasterDataService',
    'services:AuditService',
    'web.pages:router',
]
_WIRED: list[str] = []
_FAILED: dict[str, str] = {}


def _wire() -> None:
    for seam in _SEAMS:
        module_path, _, attr = seam.partition(":")
        try:
            module = importlib.import_module(f"app.{module_path}")
        except Exception as exc:  # component not present/complete yet
            log.warning("seam %s not importable: %s", seam, exc)
            _FAILED[seam] = f"{type(exc).__name__}: {exc}"
            continue
        target = getattr(module, attr, None) if attr else None
        if isinstance(target, APIRouter):
            app.include_router(target)
        elif isinstance(target, type) and issubclass(target, BaseHTTPMiddleware):
            # A middleware seam is INSTALLED, not merely imported. Importing it and moving
            # on counted the seam as wired while the middleware never ran: an app that
            # declared a request-filtering middleware deployed green with that filter
            # absent from the request path entirely, because nothing ever added it.
            # Installed here so a declared middleware is actually in force.
            app.add_middleware(target)
        _WIRED.append(seam)


_wire()


@app.on_event("startup")
def _seed_master_data_on_startup() -> None:
    """Load the specified master data once the app is up.

    `seed_master_data` is idempotent (each table is seeded only from a zero-row state) and was
    generated with no caller, so it never ran: the deployed app's Location/Vendor/Type/Purpose tables
    were EMPTY. Every dropdown on the instrument and reservation forms was blank, and saving an
    instrument answered HTTP 500 with a ForeignKeyViolation -- `location_id=1 is not present in table
    "locations"` -- because there was no row 1 to point at. The release's functional check found it as
    `form_server_error`; nothing static could, because the code is correct and only the data was absent.

    Failure here must not stop the app: a seeding problem is a data problem, and /health answering the
    truth is more useful than a container that will not start.
    """
    try:
        module = importlib.import_module("app.models.seed")
    except Exception as exc:
        log.warning("seed module not importable: %s", exc)
        return
    seeder = getattr(module, "seed_master_data", None)
    if seeder is None:
        return
    try:
        seeder()
        log.info("master data seeded")
    except Exception as exc:
        log.warning("master-data seeding failed: %s", exc)
if _FAILED and not os.environ.get("SHIFT_ALLOW_PARTIAL_SEAMS"):
    # Refuse to serve a fraction of the app. A container that exits is caught in seconds
    # and its reason is right here; a container that starts half-built looks healthy.
    _detail = "; ".join(f"{seam}: {error}" for seam, error in sorted(_FAILED.items()))
    raise RuntimeError(
        f"refusing to start: {len(_FAILED)} of {len(_SEAMS)} declared components failed to "
        f"import -- {_detail}. Set SHIFT_ALLOW_PARTIAL_SEAMS=1 to start anyway."
    )


@app.get("/health")
def health():
    """OK once at least one declared component wired; 503 while none has.

    The failure detail is included so a deploy log says WHICH components are
    missing rather than only that the app is unhealthy."""
    body = {
        "status": "ok" if (_WIRED or not _SEAMS) else "unwired",
        "wired": sorted(_WIRED),
        "failed": _FAILED,
    }
    if _SEAMS and not _WIRED:
        return JSONResponse(body, status_code=503)
    return body
